### ISSUE TITLE
FlatMap

### ISSUE THREAD

**Issue by thomassuckow** [bert2/Nullable.Extensions#13]
Would be nice if Map could take a function that also returns a nullable and have it 'do the right thing'

`T2? T1?.Map<T1, T2>(Func<T1, T2> mapping)`

`T2? T1?.FlatMap<T1, T2>(Func<T1, T2?> mapping)`

I think it could be an overload of Map, but I referred to it as flatmap since that is what Scala called the same operation.

**Comment by thomassuckow** [comment]
Of course it is called `Bind` and I'm blind.

**Comment by bert2** [comment]
If I had to do it again, I'd probably call it `FlatMap()` instead of `Bind()`. Even though I think `Bind()` is more correct, it is also less common and sounds a tad too generic...
